# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1287, 1024)
        MainWindow.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.background = QtWidgets.QWidget(MainWindow)
        self.background.setObjectName("background")
        
        self.blueckground = QtWidgets.QWidget(self.background)
        self.blueckground.setGeometry(QtCore.QRect(0, 22, 1366, 1002))
        self.blueckground.setStyleSheet("background-color:rgb(30, 47, 151);")
        self.blueckground.setObjectName("blueckground")
        
        self.whiteframe = QtWidgets.QWidget(self.blueckground)
        self.whiteframe.setGeometry(QtCore.QRect(110, 109, 831, 780))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.whiteframe.setFont(font)
        self.whiteframe.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius:100px;")
        self.whiteframe.setObjectName("whiteframe")
        
        # Welcome back text
        self.welcomeback = QtWidgets.QLabel(self.whiteframe)
        self.welcomeback.setGeometry(QtCore.QRect(100, 20, 480, 174))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(35)        
        self.welcomeback.setFont(font)
        self.welcomeback.setStyleSheet("color:rgb(30, 47, 151);")
        self.welcomeback.setObjectName("welcomeback")
        
        # Login Text
        self.login = QtWidgets.QLabel(self.whiteframe)
        self.login.setGeometry(QtCore.QRect(100, 170, 294, 53))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        font.setUnderline(False)        
        self.login.setFont(font)
        self.login.setStyleSheet("color:rgb(210, 20, 4)")
        self.login.setObjectName("login")
        
        # Fill in Use Name
        self.username = QtWidgets.QLineEdit(self.whiteframe)
        self.username.setGeometry(QtCore.QRect(100, 280, 588, 110))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)        
        self.username.setFont(font)
        self.username.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n""border: none;\n""border-bottom: 2px solid rgb(30, 47, 151);\n"
"color: rgba(0, 0, 0, 240);\n""padding-bottom: 7px;")
        self.username.setObjectName("username")
        
        # Set Passowrd
        self.password = QtWidgets.QLineEdit(self.whiteframe)
        self.password.setGeometry(QtCore.QRect(100, 430, 588, 110))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n""border: none;\n""border-bottom: 2px solid rgb(30, 47, 151);\n"
"color: rgba(0, 0, 0, 240);\n""padding-bottom: 7px;")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        
        # Forgot Password Button
        self.forgotpassword = QtWidgets.QPushButton(self.whiteframe)
        self.forgotpassword.setGeometry(QtCore.QRect(100, 630, 271, 54))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.forgotpassword.setFont(font)
        self.forgotpassword.setObjectName("forgotpassword")
        
        # Login Button
        self.loginbutton = QtWidgets.QPushButton(self.whiteframe)
        self.loginbutton.setGeometry(QtCore.QRect(450, 610, 235, 101))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.loginbutton.setFont(font)
        self.loginbutton.setStyleSheet("background-color: rgb(30, 47, 151);\n""border-radius: 30px;\n""color: rgba(255, 255, 255);\n""")
        self.loginbutton.setObjectName("loginbutton")
        
        # Medic World Icon
        self.medicworld = QtWidgets.QLabel(self.whiteframe)
        self.medicworld.setGeometry(QtCore.QRect(550, 80, 201, 211))
        self.medicworld.setStyleSheet("background-image: url(:/newPrefix/logo.png);")
        self.medicworld.setText("")
        self.medicworld.setObjectName("medicworld")
        
        # Fun Icon
        self.icon = QtWidgets.QLabel(self.blueckground)
        self.icon.setGeometry(QtCore.QRect(990, 740, 300, 286))
        self.icon.setStyleSheet("background-image: url(:/newPrefix/vector.png);")
        self.icon.setText("")
        self.icon.setObjectName("icon")
        
        # Ipad Status Bar
        self.statusbar = QtWidgets.QLabel(self.background)
        self.statusbar.setGeometry(QtCore.QRect(-2, 0, 1368, 22))
        self.statusbar.setStyleSheet("background-image: url(:/newPrefix/iPad Status bar.png);")
        self.statusbar.setText("")
        self.statusbar.setObjectName("statusbar")
        
        MainWindow.setCentralWidget(self.background)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.welcomeback.setText(_translate("MainWindow", "<html><head/><body><p>Welcome <span style=\" font-weight:600;\">Back</span></p></body></html>"))
        self.login.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" text-decoration: underline;\">LOGIN</span></p></body></html>"))
        self.username.setPlaceholderText(_translate("MainWindow", "User Name"))
        self.password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.forgotpassword.setText(_translate("MainWindow", "Forgot your Password?"))
        self.loginbutton.setText(_translate("MainWindow", "LOGIN"))
        
import test_rc
