# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patient.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewPatient(object):
    def setupUi(self, NewPatient):
        NewPatient.setObjectName("NewPatient")
        NewPatient.resize(1023, 655)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NewPatient.sizePolicy().hasHeightForWidth())
        NewPatient.setSizePolicy(sizePolicy)
        NewPatient.setLayoutDirection(QtCore.Qt.LeftToRight)
        NewPatient.setStyleSheet("background-color:#152238")
        self.centralwidget = QtWidgets.QWidget(NewPatient)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, -30, 1021, 671))
        self.scrollArea.setMinimumSize(QtCore.QSize(150, 0))
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1009, 914))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.SexLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SexLabel.sizePolicy().hasHeightForWidth())
        self.SexLabel.setSizePolicy(sizePolicy)
        self.SexLabel.setMinimumSize(QtCore.QSize(68, 73))
        self.SexLabel.setStyleSheet("\n"
                                    "font-family: \'Roboto\';\n"
                                    "font-style: normal;\n"
                                    "font-weight: 500;\n"
                                    "font-size: 24px;\n"
                                    "line-height: 28px;\n"
                                    "\n"
                                    "color: #FFFFFF;\n"
                                    "\n"
                                    "")
        self.SexLabel.setTextFormat(QtCore.Qt.RichText)
        self.SexLabel.setObjectName("SexLabel")
        self.gridLayout.addWidget(self.SexLabel, 11, 1, 1, 2)
        self.firstNameEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.firstNameEdit.sizePolicy().hasHeightForWidth())
        self.firstNameEdit.setSizePolicy(sizePolicy)
        self.firstNameEdit.setMinimumSize(QtCore.QSize(350, 57))
        self.firstNameEdit.setStyleSheet("border : 0px;\n"
                                         "background: #FFFFFF;\n"
                                         "\n"
                                         "\n"
                                         "font-family: \'Roboto\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 200;\n"
                                         "font-size: 20px;\n"
                                         "line-height: 23px;\n"
                                         "\n"
                                         "color: rgba(0, 0, 0, 0.8);\n"
                                         "\n"
                                         "")
        self.firstNameEdit.setText("")
        self.firstNameEdit.setCursorPosition(0)
        self.firstNameEdit.setObjectName("firstNameEdit")
        self.gridLayout.addWidget(self.firstNameEdit, 4, 1, 1, 2)
        self.heightEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightEdit.sizePolicy().hasHeightForWidth())
        self.heightEdit.setSizePolicy(sizePolicy)
        self.heightEdit.setMinimumSize(QtCore.QSize(350, 57))
        self.heightEdit.setStyleSheet("border : 0px;\n"
                                      "background: #FFFFFF;\n"
                                      "\n"
                                      "\n"
                                      "font-family: \'Roboto\';\n"
                                      "font-style: normal;\n"
                                      "font-weight: 200;\n"
                                      "font-size: 20px;\n"
                                      "line-height: 23px;\n"
                                      "\n"
                                      "color: rgba(0, 0, 0, 0.8);\n"
                                      "\n"
                                      "")
        self.heightEdit.setText("")
        self.heightEdit.setCursorPosition(0)
        self.heightEdit.setObjectName("heightEdit")
        self.gridLayout.addWidget(self.heightEdit, 4, 4, 1, 1)
        self.weightEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weightEdit.sizePolicy().hasHeightForWidth())
        self.weightEdit.setSizePolicy(sizePolicy)
        self.weightEdit.setMinimumSize(QtCore.QSize(350, 57))
        self.weightEdit.setStyleSheet("border : 0px;\n"
                                      "background: #FFFFFF;\n"
                                      "\n"
                                      "\n"
                                      "font-family: \'Roboto\';\n"
                                      "font-style: normal;\n"
                                      "font-weight: 200;\n"
                                      "font-size: 20px;\n"
                                      "line-height: 23px;\n"
                                      "\n"
                                      "color: rgba(0, 0, 0, 0.8);\n"
                                      "\n"
                                      "")
        self.weightEdit.setText("")
        self.weightEdit.setCursorPosition(0)
        self.weightEdit.setObjectName("weightEdit")
        self.gridLayout.addWidget(self.weightEdit, 6, 4, 1, 1)
        self.heightLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightLabel.sizePolicy().hasHeightForWidth())
        self.heightLabel.setSizePolicy(sizePolicy)
        self.heightLabel.setMinimumSize(QtCore.QSize(68, 73))
        self.heightLabel.setStyleSheet("\n"
                                       "font-family: \'Roboto\';\n"
                                       "font-style: normal;\n"
                                       "font-weight: 500;\n"
                                       "font-size: 24px;\n"
                                       "line-height: 28px;\n"
                                       "\n"
                                       "color: #FFFFFF;\n"
                                       "\n"
                                       "")
        self.heightLabel.setTextFormat(QtCore.Qt.RichText)
        self.heightLabel.setObjectName("heightLabel")
        self.gridLayout.addWidget(self.heightLabel, 1, 4, 1, 1)
        self.fnameLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fnameLabel.sizePolicy().hasHeightForWidth())
        self.fnameLabel.setSizePolicy(sizePolicy)
        self.fnameLabel.setMinimumSize(QtCore.QSize(68, 73))
        self.fnameLabel.setStyleSheet("\n"
                                      "font-family: \'Roboto\';\n"
                                      "font-style: normal;\n"
                                      "font-weight: 500;\n"
                                      "font-size: 24px;\n"
                                      "line-height: 28px;\n"
                                      "\n"
                                      "color: #FFFFFF;\n"
                                      "\n"
                                      "")
        self.fnameLabel.setTextFormat(QtCore.Qt.RichText)
        self.fnameLabel.setObjectName("fnameLabel")
        self.gridLayout.addWidget(self.fnameLabel, 1, 1, 1, 3)
        self.roomtEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roomtEdit.sizePolicy().hasHeightForWidth())
        self.roomtEdit.setSizePolicy(sizePolicy)
        self.roomtEdit.setMinimumSize(QtCore.QSize(350, 57))
        self.roomtEdit.setStyleSheet("border : 0px;\n"
                                     "background: #FFFFFF;\n"
                                     "\n"
                                     "\n"
                                     "font-family: \'Roboto\';\n"
                                     "font-style: normal;\n"
                                     "font-weight: 200;\n"
                                     "font-size: 20px;\n"
                                     "line-height: 23px;\n"
                                     "\n"
                                     "color: rgba(0, 0, 0, 0.8);\n"
                                     "\n"
                                     "")
        self.roomtEdit.setText("")
        self.roomtEdit.setCursorPosition(0)
        self.roomtEdit.setObjectName("roomtEdit")
        self.gridLayout.addWidget(self.roomtEdit, 8, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.weightLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.weightLabel.setStyleSheet("\n"
                                       "font-family: \'Roboto\';\n"
                                       "font-style: normal;\n"
                                       "font-weight: 500;\n"
                                       "font-size: 24px;\n"
                                       "line-height: 28px;\n"
                                       "\n"
                                       "color: #FFFFFF;\n"
                                       "\n"
                                       "")
        self.weightLabel.setTextFormat(QtCore.Qt.RichText)
        self.weightLabel.setObjectName("weightLabel")
        self.gridLayout.addWidget(self.weightLabel, 5, 4, 1, 1)
        self.ssnEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssnEdit.sizePolicy().hasHeightForWidth())
        self.ssnEdit.setSizePolicy(sizePolicy)
        self.ssnEdit.setMinimumSize(QtCore.QSize(350, 57))
        self.ssnEdit.setStyleSheet("border : 0px;\n"
                                   "background: #FFFFFF;\n"
                                   "\n"
                                   "\n"
                                   "font-family: \'Roboto\';\n"
                                   "font-style: normal;\n"
                                   "font-weight: 200;\n"
                                   "font-size: 20px;\n"
                                   "line-height: 23px;\n"
                                   "\n"
                                   "color: rgba(0, 0, 0, 0.8);\n"
                                   "\n"
                                   "")
        self.ssnEdit.setText("")
        self.ssnEdit.setCursorPosition(0)
        self.ssnEdit.setObjectName("ssnEdit")
        self.gridLayout.addWidget(self.ssnEdit, 10, 1, 1, 1)
        self.roomLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.roomLabel.setStyleSheet("\n"
                                     "font-family: \'Roboto\';\n"
                                     "font-style: normal;\n"
                                     "font-weight: 500;\n"
                                     "font-size: 24px;\n"
                                     "line-height: 28px;\n"
                                     "\n"
                                     "color: #FFFFFF;\n"
                                     "\n"
                                     "")
        self.roomLabel.setTextFormat(QtCore.Qt.RichText)
        self.roomLabel.setObjectName("roomLabel")
        self.gridLayout.addWidget(self.roomLabel, 7, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(60, 17, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 5, 1, 1)
        self.emailEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emailEdit.sizePolicy().hasHeightForWidth())
        self.emailEdit.setSizePolicy(sizePolicy)
        self.emailEdit.setMinimumSize(QtCore.QSize(350, 57))
        self.emailEdit.setStyleSheet("border : 0px;\n"
                                     "background: #FFFFFF;\n"
                                     "\n"
                                     "\n"
                                     "font-family: \'Roboto\';\n"
                                     "font-style: normal;\n"
                                     "font-weight: 200;\n"
                                     "font-size: 20px;\n"
                                     "line-height: 23px;\n"
                                     "\n"
                                     "color: rgba(0, 0, 0, 0.8);\n"
                                     "\n"
                                     "")
        self.emailEdit.setText("")
        self.emailEdit.setCursorPosition(0)
        self.emailEdit.setObjectName("emailEdit")
        self.gridLayout.addWidget(self.emailEdit, 8, 1, 1, 1)
        self.phoneEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phoneEdit.sizePolicy().hasHeightForWidth())
        self.phoneEdit.setSizePolicy(sizePolicy)
        self.phoneEdit.setMinimumSize(QtCore.QSize(350, 57))
        self.phoneEdit.setStyleSheet("border : 0px;\n"
                                     "background: #FFFFFF;\n"
                                     "\n"
                                     "\n"
                                     "font-family: \'Roboto\';\n"
                                     "font-style: normal;\n"
                                     "font-weight: 200;\n"
                                     "font-size: 20px;\n"
                                     "line-height: 23px;\n"
                                     "\n"
                                     "color: rgba(0, 0, 0, 0.8);\n"
                                     "\n"
                                     "")
        self.phoneEdit.setText("")
        self.phoneEdit.setCursorPosition(0)
        self.phoneEdit.setObjectName("phoneEdit")
        self.gridLayout.addWidget(self.phoneEdit, 10, 4, 1, 1)
        self.lastNameEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lastNameEdit.sizePolicy().hasHeightForWidth())
        self.lastNameEdit.setSizePolicy(sizePolicy)
        self.lastNameEdit.setMinimumSize(QtCore.QSize(350, 57))
        self.lastNameEdit.setStyleSheet("border : 0px;\n"
                                        "background: #FFFFFF;\n"
                                        "\n"
                                        "\n"
                                        "font-family: \'Roboto\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 200;\n"
                                        "font-size: 20px;\n"
                                        "line-height: 23px;\n"
                                        "\n"
                                        "color: rgba(0, 0, 0, 0.8);\n"
                                        "\n"
                                        "")
        self.lastNameEdit.setText("")
        self.lastNameEdit.setCursorPosition(0)
        self.lastNameEdit.setObjectName("lastNameEdit")
        self.gridLayout.addWidget(self.lastNameEdit, 6, 1, 1, 1)
        self.ssnLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssnLabel.sizePolicy().hasHeightForWidth())
        self.ssnLabel.setSizePolicy(sizePolicy)
        self.ssnLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.ssnLabel.setStyleSheet("\n"
                                    "font-family: \'Roboto\';\n"
                                    "font-style: normal;\n"
                                    "font-weight: 500;\n"
                                    "font-size: 24px;\n"
                                    "line-height: 28px;\n"
                                    "\n"
                                    "color: #FFFFFF;\n"
                                    "\n"
                                    "")
        self.ssnLabel.setTextFormat(QtCore.Qt.RichText)
        self.ssnLabel.setObjectName("ssnLabel")
        self.gridLayout.addWidget(self.ssnLabel, 9, 1, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 44, 20)
        self.horizontalLayout.setSpacing(27)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.maleButton = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.maleButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.maleButton.setAutoFillBackground(False)
        self.maleButton.setStyleSheet("\n"
                                      "font-family: \'Roboto\';\n"
                                      "font-style: normal;\n"
                                      "font-weight: 300;\n"
                                      "font-size: 24px;\n"
                                      "line-height: 28px;\n"
                                      "\n"
                                      "color: #FFFFFF;\n"
                                      "\n"
                                      "")
        self.maleButton.setObjectName("maleButton")
        self.horizontalLayout.addWidget(self.maleButton)
        self.femaleButton = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.femaleButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.femaleButton.setStyleSheet("\n"
                                        "font-family: \'Roboto\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 300;\n"
                                        "font-size: 24px;\n"
                                        "line-height: 28px;\n"
                                        "\n"
                                        "color: #FFFFFF;\n"
                                        "\n"
                                        "")
        self.femaleButton.setIconSize(QtCore.QSize(28, 28))
        self.femaleButton.setObjectName("femaleButton")
        self.horizontalLayout.addWidget(self.femaleButton)
        self.gridLayout.addLayout(self.horizontalLayout, 12, 1, 1, 1)
        self.lnameLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnameLabel.sizePolicy().hasHeightForWidth())
        self.lnameLabel.setSizePolicy(sizePolicy)
        self.lnameLabel.setMinimumSize(QtCore.QSize(68, 73))
        self.lnameLabel.setStyleSheet("\n"
                                      "font-family: \'Roboto\';\n"
                                      "font-style: normal;\n"
                                      "font-weight: 500;\n"
                                      "font-size: 24px;\n"
                                      "line-height: 28px;\n"
                                      "\n"
                                      "color: #FFFFFF;\n"
                                      "\n"
                                      "")
        self.lnameLabel.setTextFormat(QtCore.Qt.RichText)
        self.lnameLabel.setObjectName("lnameLabel")
        self.gridLayout.addWidget(self.lnameLabel, 5, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 58, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        self.phoneLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phoneLabel.sizePolicy().hasHeightForWidth())
        self.phoneLabel.setSizePolicy(sizePolicy)
        self.phoneLabel.setMinimumSize(QtCore.QSize(68, 73))
        self.phoneLabel.setStyleSheet("\n"
                                      "font-family: \'Roboto\';\n"
                                      "font-style: normal;\n"
                                      "font-weight: 500;\n"
                                      "font-size: 24px;\n"
                                      "line-height: 28px;\n"
                                      "\n"
                                      "color: #FFFFFF;\n"
                                      "\n"
                                      "")
        self.phoneLabel.setTextFormat(QtCore.Qt.RichText)
        self.phoneLabel.setObjectName("phoneLabel")
        self.gridLayout.addWidget(self.phoneLabel, 9, 4, 1, 1)
        self.emailLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emailLabel.sizePolicy().hasHeightForWidth())
        self.emailLabel.setSizePolicy(sizePolicy)
        self.emailLabel.setMinimumSize(QtCore.QSize(68, 73))
        self.emailLabel.setStyleSheet("\n"
                                      "font-family: \'Roboto\';\n"
                                      "font-style: normal;\n"
                                      "font-weight: 500;\n"
                                      "font-size: 24px;\n"
                                      "line-height: 28px;\n"
                                      "\n"
                                      "color: #FFFFFF;\n"
                                      "\n"
                                      "")
        self.emailLabel.setTextFormat(QtCore.Qt.RichText)
        self.emailLabel.setObjectName("emailLabel")
        self.gridLayout.addWidget(self.emailLabel, 7, 1, 1, 1)
        self.cancelPatientButon = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.cancelPatientButon.setMaximumSize(QtCore.QSize(180, 60))
        self.cancelPatientButon.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cancelPatientButon.setStyleSheet("\n"
                                              "\n"
                                              "background: #D21404;\n"
                                              "border-radius: 10px;\n"
                                              "\n"
                                              "font-family: \'Roboto\';\n"
                                              "font-style: normal;\n"
                                              "font-weight: 700;\n"
                                              "font-size: 24px;\n"
                                              "line-height: 28px;\n"
                                              "text-align: center;\n"
                                              "color: #FFFFFF;\n"
                                              "\n"
                                              "")
        self.cancelPatientButon.setObjectName("cancelPatientButon")
        self.gridLayout.addWidget(self.cancelPatientButon, 14, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 58, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 13, 1, 1, 1)
        self.confirmPatientButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.confirmPatientButton.setMaximumSize(QtCore.QSize(180, 60))
        self.confirmPatientButton.setStyleSheet("\n"
                                                "position: absolute;\n"
                                                "width: 180px;\n"
                                                "height: 60px;\n"
                                                "left: 660px;\n"
                                                "top: 542px;\n"
                                                "\n"
                                                "background: #1E2F97;\n"
                                                "border-radius: 10px;\n"
                                                "\n"
                                                "font-family: \'Roboto\';\n"
                                                "font-style: normal;\n"
                                                "font-weight: 700;\n"
                                                "font-size: 24px;\n"
                                                "line-height: 28px;\n"
                                                "text-align: center;\n"
                                                "\n"
                                                "color: #FFFFFF;\n"
                                                "\n"
                                                "")
        self.confirmPatientButton.setObjectName("confirmPatientButton")
        self.gridLayout.addWidget(self.confirmPatientButton, 14, 4, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        NewPatient.setCentralWidget(self.centralwidget)

        self.retranslateUi(NewPatient)
        QtCore.QMetaObject.connectSlotsByName(NewPatient)

    def retranslateUi(self, NewPatient):
        _translate = QtCore.QCoreApplication.translate
        NewPatient.setWindowTitle(_translate("NewPatient", "New Patient Form"))
        self.SexLabel.setText(_translate("NewPatient",
                                         "<html><head/><body><p><span style=\" font-size:18pt; color:#d21404;\">* </span><span style=\" font-size:18pt; color:#ffffff;\">Patient\'s Sex</span></p></body></html>"))
        self.firstNameEdit.setPlaceholderText(_translate("NewPatient", "Enter Patient\'s First Name"))
        self.heightEdit.setPlaceholderText(_translate("NewPatient", "Enter Patient\'s Height"))
        self.weightEdit.setPlaceholderText(_translate("NewPatient", "Enter Patient\'s Weight"))
        self.heightLabel.setText(_translate("NewPatient",
                                            "<html><head/><body><p><span style=\" font-size:18pt; color:#ffffff;\">Patient\'s Height</span></p></body></html>"))
        self.fnameLabel.setText(_translate("NewPatient",
                                           "<html><head/><body><p><span style=\" font-size:18pt; color:#d21404;\">* </span><span style=\" font-size:18pt; color:#ffffff;\">Patient\'s First Name</span></p></body></html>"))
        self.roomtEdit.setPlaceholderText(_translate("NewPatient", "Enter Patient\'s Room"))
        self.weightLabel.setText(_translate("NewPatient",
                                            "<html><head/><body><p><span style=\" font-size:18pt; color:#ffffff;\">Patient\'s Weight</span></p></body></html>"))
        self.ssnEdit.setPlaceholderText(_translate("NewPatient", "Enter Patient\'s SSN"))
        self.roomLabel.setText(_translate("NewPatient",
                                          "<html><head/><body><p><span style=\" font-size:18pt; color:#ffffff;\">Patient\'s Room</span></p></body></html>"))
        self.emailEdit.setPlaceholderText(_translate("NewPatient", "Enter Patient\'s Email"))
        self.phoneEdit.setPlaceholderText(_translate("NewPatient", "Enter Patient\'s Phone"))
        self.lastNameEdit.setPlaceholderText(_translate("NewPatient", "Enter Patient\'s Last Name"))
        self.ssnLabel.setText(_translate("NewPatient",
                                         "<html><head/><body><p><span style=\" font-size:18pt; color:#d21404;\">* </span><span style=\" font-size:18pt; color:#ffffff;\">Patient\'s Social Security Number</span></p></body></html>"))
        self.maleButton.setText(_translate("NewPatient", "Male"))
        self.femaleButton.setText(_translate("NewPatient", "Female"))
        self.lnameLabel.setText(_translate("NewPatient",
                                           "<html><head/><body><p><span style=\" font-size:18pt; color:#d21404;\">* </span><span style=\" font-size:18pt; color:#ffffff;\">Patient\'s Last Name</span></p></body></html>"))
        self.phoneLabel.setText(_translate("NewPatient",
                                           "<html><head/><body><p><span style=\" font-size:18pt; color:#ffffff;\">Patient\'s Phone</span></p></body></html>"))
        self.emailLabel.setText(_translate("NewPatient",
                                           "<html><head/><body><p><span style=\" font-size:18pt; color:#d21404;\">* </span><span style=\" font-size:18pt; color:#ffffff;\">Patient\'s Email</span></p></body></html>"))
        self.cancelPatientButon.setText(_translate("NewPatient", "CANCEL"))
        self.confirmPatientButton.setText(_translate("NewPatient", "CONFIRM"))
