DASHBOARD_CLICKED = "QPushButton{\n image: url(:/img/img/home icon.png);\nborder:none;\n"
"font-size:20px;\n"
"font-family:Roboto;\n"
"color: #FFFFFF;\n"
"background-color: #7434A4;\n"
"}"

DASHBOARD_ON = "QPushButton{\n"
"   image: url(:/img/img/home icon.png);\n"
"\n"
"border:none;\n"
"font-size:20px;\n"
"font-family:Roboto;\n"
"color: #FFFFFF;\n"
"background-color: #152238;\n"
"}\n"
