# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainPage(object):
    def setupUi(self, mainPage):
        mainPage.setObjectName("mainPage")
        mainPage.resize(1366, 982)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(mainPage)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.topBarFrame = QtWidgets.QFrame(mainPage)
        self.topBarFrame.setMaximumSize(QtCore.QSize(1366, 117))
        font = QtGui.QFont()
        font.setBold(True)
        self.topBarFrame.setFont(font)
        self.topBarFrame.setStyleSheet("background-color:#ffffff;")
        self.topBarFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topBarFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topBarFrame.setObjectName("topBarFrame")
        self.exitButton = QtWidgets.QPushButton(self.topBarFrame)
        self.exitButton.setGeometry(QtCore.QRect(1283, 43, 40, 40))
        self.exitButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/exit icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitButton.setIcon(icon)
        self.exitButton.setIconSize(QtCore.QSize(40, 40))
        self.exitButton.setFlat(True)
        self.exitButton.setObjectName("exitButton")
        self.doctorName = QtWidgets.QLabel(self.topBarFrame)
        self.doctorName.setGeometry(QtCore.QRect(910, 34, 211, 78))
        self.doctorName.setTextFormat(QtCore.Qt.MarkdownText)
        self.doctorName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.doctorName.setObjectName("doctorName")
        self.timeLeft = QtWidgets.QLabel(self.topBarFrame)
        self.timeLeft.setGeometry(QtCore.QRect(610, 30, 284, 65))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeLeft.sizePolicy().hasHeightForWidth())
        self.timeLeft.setSizePolicy(sizePolicy)
        self.timeLeft.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.timeLeft.setFont(font)
        self.timeLeft.setStyleSheet("")
        self.timeLeft.setTextFormat(QtCore.Qt.AutoText)
        self.timeLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLeft.setWordWrap(True)
        self.timeLeft.setIndent(0)
        self.timeLeft.setObjectName("timeLeft")
        self.heartIcon = QtWidgets.QLabel(self.topBarFrame)
        self.heartIcon.setGeometry(QtCore.QRect(39, 38, 60, 60))
        self.heartIcon.setMaximumSize(QtCore.QSize(60, 60))
        self.heartIcon.setLineWidth(0)
        self.heartIcon.setText("")
        self.heartIcon.setPixmap(QtGui.QPixmap(":/img/img/heart rate icon.png"))
        self.heartIcon.setObjectName("heartIcon")
        self.topSearchBar = QtWidgets.QLineEdit(self.topBarFrame)
        self.topSearchBar.setGeometry(QtCore.QRect(169, 34, 405, 59))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topSearchBar.sizePolicy().hasHeightForWidth())
        self.topSearchBar.setSizePolicy(sizePolicy)
        self.topSearchBar.setMaximumSize(QtCore.QSize(405, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.topSearchBar.setFont(font)
        self.topSearchBar.setObjectName("topSearchBar")
        self.userIcon = QtWidgets.QLabel(self.topBarFrame)
        self.userIcon.setGeometry(QtCore.QRect(1153, 38, 50, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userIcon.sizePolicy().hasHeightForWidth())
        self.userIcon.setSizePolicy(sizePolicy)
        self.userIcon.setLineWidth(0)
        self.userIcon.setText("")
        self.userIcon.setPixmap(QtGui.QPixmap(":/img/img/user icon.png"))
        self.userIcon.setIndent(0)
        self.userIcon.setObjectName("userIcon")
        self.timeLeftTimer = QtWidgets.QLabel(self.topBarFrame)
        self.timeLeftTimer.setGeometry(QtCore.QRect(783, 46, 81, 31))
        self.timeLeftTimer.setStyleSheet("font-size:26px")
        self.timeLeftTimer.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLeftTimer.setObjectName("timeLeftTimer")
        self.topDateTime = QtWidgets.QLabel(self.topBarFrame)
        self.topDateTime.setGeometry(QtCore.QRect(1, 1, 170, 22))
        font = QtGui.QFont()
        font.setBold(True)
        self.topDateTime.setFont(font)
        self.topDateTime.setTextFormat(QtCore.Qt.RichText)
        self.topDateTime.setObjectName("topDateTime")
        self.heartIcon.raise_()
        self.topSearchBar.raise_()
        self.userIcon.raise_()
        self.timeLeft.raise_()
        self.exitButton.raise_()
        self.doctorName.raise_()
        self.timeLeftTimer.raise_()
        self.topDateTime.raise_()
        self.verticalLayout_2.addWidget(self.topBarFrame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(mainPage)
        self.frame.setMaximumSize(QtCore.QSize(137, 16777215))
        self.frame.setStyleSheet("background-color:#152238;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 141, 746))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dashboardButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.dashboardButton.setFont(font)
        self.dashboardButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dashboardButton.setStyleSheet("QPushButton{\n"
"    image: url(:/img/img/home icon.png);\n"
"\n"
"border:none;\n"
"font-size:20px;\n"
"font-family:Roboto;\n"
"color: #FFFFFF;\n"
"background-color: #152238;\n"
"}\n"
"")
        self.dashboardButton.setAutoRepeat(False)
        self.dashboardButton.setFlat(True)
        self.dashboardButton.setObjectName("dashboardButton")
        self.verticalLayout.addWidget(self.dashboardButton)
        self.patientsButton = QtWidgets.QPushButton(self.layoutWidget)
        self.patientsButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.patientsButton.setStyleSheet("image: url(:/img/img/users icon.png);\n"
"\n"
"\n"
"border:none;\n"
"font-size:20px;\n"
"font-family:Roboto;\n"
"color: #FFFFFF;\n"
"background-color: #152238;")
        self.patientsButton.setAutoRepeat(False)
        self.patientsButton.setFlat(True)
        self.patientsButton.setObjectName("patientsButton")
        self.verticalLayout.addWidget(self.patientsButton)
        self.checkListButton = QtWidgets.QPushButton(self.layoutWidget)
        self.checkListButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkListButton.setStyleSheet("image: url(:/img/img/check icon.png);\n"
"\n"
"border:none;\n"
"font-size:20px;\n"
"font-family:Roboto;\n"
"color: #FFFFFF;\n"
"background-color: #152238;")
        self.checkListButton.setAutoRepeat(False)
        self.checkListButton.setFlat(True)
        self.checkListButton.setObjectName("checkListButton")
        self.verticalLayout.addWidget(self.checkListButton)
        self.suppliesButton = QtWidgets.QPushButton(self.layoutWidget)
        self.suppliesButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.suppliesButton.setStyleSheet("image: url(:/img/img/pharmaceutical supplies.png);\n"
"\n"
"        \n"
"\n"
"border:none;\n"
"font-size:20px;\n"
"font-family:Roboto;\n"
"color: #FFFFFF;\n"
"background-color: #152238;")
        self.suppliesButton.setAutoRepeat(False)
        self.suppliesButton.setFlat(True)
        self.suppliesButton.setObjectName("suppliesButton")
        self.verticalLayout.addWidget(self.suppliesButton)
        self.messagesButton = QtWidgets.QPushButton(self.layoutWidget)
        self.messagesButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.messagesButton.setStyleSheet("image: url(:/img/img/envelope vector.png);\n"
"\n"
"        \n"
"border:none;\n"
"font-size:20px;\n"
"font-family:Roboto;\n"
"color: #FFFFFF;\n"
"background-color: #152238;")
        self.messagesButton.setAutoRepeat(False)
        self.messagesButton.setFlat(True)
        self.messagesButton.setObjectName("messagesButton")
        self.verticalLayout.addWidget(self.messagesButton)
        self.newsroomButton = QtWidgets.QPushButton(self.layoutWidget)
        self.newsroomButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.newsroomButton.setStyleSheet("\n"
"image: url(:/img/img/pngkey 1.png);\n"
"\n"
"        \n"
"border:none;\n"
"font-size:20px;\n"
"font-family:Roboto;\n"
"color: #FFFFFF;\n"
"background-color: #152238;")
        self.newsroomButton.setAutoRepeat(False)
        self.newsroomButton.setFlat(True)
        self.newsroomButton.setObjectName("newsroomButton")
        self.verticalLayout.addWidget(self.newsroomButton)
        self.settingButton = QtWidgets.QPushButton(self.layoutWidget)
        self.settingButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.settingButton.setStyleSheet("image: url(:/img/img/gear icon.png);\n"
"\n"
"\n"
"border:none;\n"
"font-size:20px;\n"
"font-family:Roboto;\n"
"color: #FFFFFF;\n"
"background-color: #152238;")
        self.settingButton.setAutoRepeat(False)
        self.settingButton.setFlat(True)
        self.settingButton.setObjectName("settingButton")
        self.verticalLayout.addWidget(self.settingButton)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(mainPage)
        self.frame_2.setStyleSheet("background-color:#EEEEEE")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(mainPage)
        QtCore.QMetaObject.connectSlotsByName(mainPage)

    def retranslateUi(self, mainPage):
        _translate = QtCore.QCoreApplication.translate
        mainPage.setWindowTitle(_translate("mainPage", "Widget"))
        self.doctorName.setText(_translate("mainPage", "<html><head/><body><p align=\"right\"><span style=\" font-size:16pt; font-weight:700;\">Dr.Marios Stefanidis</span></p><p align=\"right\"><span style=\" font-size:16pt;\">Physician</span></p></body></html>"))
        self.timeLeft.setText(_translate("mainPage", "TIME <br/>LEFT"))
        self.topSearchBar.setPlaceholderText(_translate("mainPage", "Search..."))
        self.timeLeftTimer.setText(_translate("mainPage", "00:00"))
        self.topDateTime.setText(_translate("mainPage", "<html><head/><body><p><span style=\" font-size:8pt;\">Date loading...</span></p></body></html>"))
        self.dashboardButton.setText(_translate("mainPage", "\n"
"\n"
"\n"
"Dashboard"))
        self.patientsButton.setText(_translate("mainPage", "\n"
"\n"
"\n"
"Patients"))
        self.checkListButton.setText(_translate("mainPage", "\n"
"\n"
"\n"
"\n"
"Checklist"))
        self.suppliesButton.setText(_translate("mainPage", "\n"
"\n"
"\n"
"\n"
"Supplies"))
        self.messagesButton.setText(_translate("mainPage", "\n"
"\n"
"\n"
"Messages"))
        self.newsroomButton.setText(_translate("mainPage", "\n"
"\n"
"\n"
"\n"
"Newsroom"))
        self.settingButton.setText(_translate("mainPage", "\n"
"\n"
"\n"
"Settings"))
import MainDoctorSreen.mainPageResoureces
