# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newMedicationForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1211, 907)
        Frame.setStyleSheet("background-color:#eeeeee;")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(137, 143, 394, 55))
        self.label.setStyleSheet("\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 30px;\n"
"line-height: 35px;\n"
"\n"
"color: #1E2F97;\n"
"\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setGeometry(QtCore.QRect(703, 143, 394, 55))
        self.label_2.setStyleSheet("\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 30px;\n"
"line-height: 35px;\n"
"\n"
"color: #1E2F97;\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Frame)
        self.label_3.setGeometry(QtCore.QRect(127, 214, 396, 34))
        self.label_3.setStyleSheet("\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 24px;\n"
"line-height: 28px;\n"
"\n"
"color: #000000;\n"
"\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Frame)
        self.label_4.setGeometry(QtCore.QRect(136, 263, 372, 39))
        self.label_4.setStyleSheet("\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 20px;\n"
"line-height: 23px;\n"
"\n"
"color: rgba(0, 0, 0, 0.5);\n"
"\n"
"")
        self.label_4.setObjectName("label_4")
        self.medicationTypeEdit = QtWidgets.QLineEdit(Frame)
        self.medicationTypeEdit.setGeometry(QtCore.QRect(128, 309, 414, 56))
        self.medicationTypeEdit.setStyleSheet("\n"
"background: #FFFFFF;\n"
"\n"
"border-radius: 10px;\n"
"\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 20px;\n"
"line-height: 23px;\n"
"padding:10px;\n"
"color: rgba(0, 0, 0, 0.5);\n"
"\n"
"")
        self.medicationTypeEdit.setObjectName("medicationTypeEdit")
        self.label_5 = QtWidgets.QLabel(Frame)
        self.label_5.setGeometry(QtCore.QRect(136, 457, 372, 39))
        self.label_5.setStyleSheet("\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 20px;\n"
"line-height: 23px;\n"
"\n"
"color: rgba(0, 0, 0, 0.5);\n"
"\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Frame)
        self.label_6.setGeometry(QtCore.QRect(127, 408, 396, 34))
        self.label_6.setStyleSheet("\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 24px;\n"
"line-height: 28px;\n"
"\n"
"color: #000000;\n"
"\n"
"")
        self.label_6.setObjectName("label_6")
        self.medicatonNameEdit = QtWidgets.QLineEdit(Frame)
        self.medicatonNameEdit.setGeometry(QtCore.QRect(128, 503, 414, 56))
        self.medicatonNameEdit.setStyleSheet("\n"
"background: #FFFFFF;\n"
"\n"
"border-radius: 10px;\n"
"\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 20px;\n"
"line-height: 23px;\n"
"padding:10px;\n"
"color: rgba(0, 0, 0, 0.5);\n"
"\n"
"")
        self.medicatonNameEdit.setObjectName("medicatonNameEdit")
        self.label_7 = QtWidgets.QLabel(Frame)
        self.label_7.setGeometry(QtCore.QRect(131, 638, 402, 50))
        self.label_7.setStyleSheet("\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 20px;\n"
"line-height: 23px;\n"
"\n"
"color: rgba(0, 0, 0, 0.5);\n"
"\n"
"")
        self.label_7.setObjectName("label_7")
        self.medicationQuantityEdit = QtWidgets.QLineEdit(Frame)
        self.medicationQuantityEdit.setGeometry(QtCore.QRect(127, 697, 414, 56))
        self.medicationQuantityEdit.setStyleSheet("\n"
"background: #FFFFFF;\n"
"\n"
"border-radius: 10px;\n"
"\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 20px;\n"
"line-height: 23px;\n"
"padding:10px;\n"
"color: rgba(0, 0, 0, 0.5);\n"
"\n"
"")
        self.medicationQuantityEdit.setObjectName("medicationQuantityEdit")
        self.label_8 = QtWidgets.QLabel(Frame)
        self.label_8.setGeometry(QtCore.QRect(127, 600, 367, 34))
        self.label_8.setStyleSheet("\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 24px;\n"
"line-height: 28px;\n"
"\n"
"color: #000000;\n"
"\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Frame)
        self.label_9.setGeometry(QtCore.QRect(706, 252, 402, 50))
        self.label_9.setStyleSheet("\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 20px;\n"
"line-height: 23px;\n"
"\n"
"color: rgba(0, 0, 0, 0.5);\n"
"\n"
"")
        self.label_9.setObjectName("label_9")
        self.minimumEdit = QtWidgets.QLineEdit(Frame)
        self.minimumEdit.setGeometry(QtCore.QRect(702, 311, 414, 56))
        self.minimumEdit.setStyleSheet("\n"
"background: #FFFFFF;\n"
"\n"
"border-radius: 10px;\n"
"\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 20px;\n"
"line-height: 23px;\n"
"padding:10px;\n"
"color: rgba(0, 0, 0, 0.5);\n"
"\n"
"")
        self.minimumEdit.setObjectName("minimumEdit")
        self.label_10 = QtWidgets.QLabel(Frame)
        self.label_10.setGeometry(QtCore.QRect(702, 214, 367, 34))
        self.label_10.setStyleSheet("\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 24px;\n"
"line-height: 28px;\n"
"\n"
"color: #000000;\n"
"\n"
"")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Frame)
        self.label_11.setGeometry(QtCore.QRect(706, 446, 402, 50))
        self.label_11.setStyleSheet("\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 20px;\n"
"line-height: 23px;\n"
"\n"
"color: rgba(0, 0, 0, 0.5);\n"
"\n"
"")
        self.label_11.setObjectName("label_11")
        self.mediocreEdit = QtWidgets.QLineEdit(Frame)
        self.mediocreEdit.setGeometry(QtCore.QRect(702, 505, 414, 56))
        self.mediocreEdit.setStyleSheet("\n"
"background: #FFFFFF;\n"
"\n"
"border-radius: 10px;\n"
"\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 20px;\n"
"line-height: 23px;\n"
"padding:10px;\n"
"color: rgba(0, 0, 0, 0.5);\n"
"\n"
"")
        self.mediocreEdit.setObjectName("mediocreEdit")
        self.label_12 = QtWidgets.QLabel(Frame)
        self.label_12.setGeometry(QtCore.QRect(702, 408, 367, 34))
        self.label_12.setStyleSheet("\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 24px;\n"
"line-height: 28px;\n"
"\n"
"color: #000000;\n"
"\n"
"")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Frame)
        self.label_13.setGeometry(QtCore.QRect(715, 636, 402, 50))
        self.label_13.setStyleSheet("\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 20px;\n"
"line-height: 23px;\n"
"\n"
"color: rgba(0, 0, 0, 0.5);\n"
"\n"
"")
        self.label_13.setObjectName("label_13")
        self.lowEdit = QtWidgets.QLineEdit(Frame)
        self.lowEdit.setGeometry(QtCore.QRect(711, 695, 414, 56))
        self.lowEdit.setStyleSheet("\n"
"background: #FFFFFF;\n"
"\n"
"border-radius: 10px;\n"
"\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 20px;\n"
"line-height: 23px;\n"
"padding:10px;\n"
"color: rgba(0, 0, 0, 0.5);\n"
"\n"
"")
        self.lowEdit.setObjectName("lowEdit")
        self.label_14 = QtWidgets.QLabel(Frame)
        self.label_14.setGeometry(QtCore.QRect(711, 598, 367, 34))
        self.label_14.setStyleSheet("\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 24px;\n"
"line-height: 28px;\n"
"\n"
"color: #000000;\n"
"\n"
"")
        self.label_14.setObjectName("label_14")
        self.cancelButton = QtWidgets.QPushButton(Frame)
        self.cancelButton.setGeometry(QtCore.QRect(226, 800, 180, 60))
        self.cancelButton.setStyleSheet("\n"
"border-radius: 10px;\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 24px;\n"
"line-height: 28px;\n"
"text-align: center;\n"
"background-color:#d21404;\n"
"color: #ffffff;\n"
"\n"
"")
        self.cancelButton.setObjectName("cancelButton")
        self.doneButton = QtWidgets.QPushButton(Frame)
        self.doneButton.setGeometry(QtCore.QRect(827, 800, 180, 60))
        self.doneButton.setStyleSheet("\n"
"border-radius: 10px;\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 24px;\n"
"line-height: 28px;\n"
"text-align: center;\n"
"background-color:#0026CA;\n"
"color: #ffffff;\n"
"\n"
"")
        self.doneButton.setObjectName("doneButton")
        self.label_15 = QtWidgets.QLabel(Frame)
        self.label_15.setGeometry(QtCore.QRect(343, 33, 479, 65))
        self.label_15.setStyleSheet("\n"
"\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 38px;\n"
"line-height: 45px;\n"
"text-align: center;\n"
"\n"
"color: #1E2F97;\n"
"\n"
"")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.backButton = QtWidgets.QPushButton(Frame)
        self.backButton.setGeometry(QtCore.QRect(60, 40, 30, 46))
        self.backButton.setStyleSheet("\n"
"border-radius: 10px;\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 24px;\n"
"line-height: 28px;\n"
"text-align: center;\n"
"background-color:#eeeeee;\n"
"\n"
"\n"
"")
        self.backButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/img/back button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backButton.setIcon(icon)
        self.backButton.setIconSize(QtCore.QSize(30, 46))
        self.backButton.setObjectName("backButton")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "Medication Details:"))
        self.label_2.setText(_translate("Frame", "Quantity Details:"))
        self.label_3.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:18pt; color:#d21404;\">*</span><span style=\" font-size:18pt;\">Type of Medication:</span></p></body></html>"))
        self.label_4.setText(_translate("Frame", "Enter Type of Medication( Antibiotics etc.)"))

        self.label_5.setText(_translate("Frame", "Enter Name of Medication (Morphine etc.)"))
        self.label_6.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:18pt; color:#d21404;\">*</span><span style=\" font-size:18pt;\">Name of Medication:</span></p></body></html>"))
        self.label_7.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:15pt;\">Enter Current Quantity of Medication( 2 boxes<br/> etc.)</span></p></body></html>"))
        self.label_8.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:18pt; color:#d21404;\">*</span><span style=\" font-size:18pt;\">Quantity of Medication:</span></p></body></html>"))
        self.label_9.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:15pt;\">Enter minimum quantity considerd to be<br/>fully stocked</span></p></body></html>"))
        self.label_10.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:18pt; color:#d21404;\">*</span><span style=\" font-size:18pt;\">Minimum:</span></p></body></html>"))
        self.label_11.setText(_translate("Frame", "<html><head/><body><p>Enter a quantity considered to be semi -<br/>stocked</p></body></html>"))
        self.label_12.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:18pt; color:#d21404;\">*</span><span style=\" font-size:18pt;\">Mediocre:</span></p></body></html>"))
        self.label_13.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:15pt;\">Enter a maximum quantity considered to be<br/>almost out of stock</span></p></body></html>"))
        self.label_14.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:18pt; color:#d21404;\">*</span><span style=\" font-size:18pt;\">Low:</span></p></body></html>"))
        self.cancelButton.setText(_translate("Frame", "CANCEL"))
        self.doneButton.setText(_translate("Frame", "DONE"))
        self.label_15.setText(_translate("Frame", "New Medicine"))


import MainGUI.resources
