# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messages.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MessagesGui(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1231, 871)
        Frame.setStyleSheet("background-color:#EEEEEE")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
import MainGUI.resources