# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'successFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(549, 437)
        MainWindow.setStyleSheet("background-color:#eeeeee")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 20, 501, 391))
        self.frame.setStyleSheet("background-color:#ffffff")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 30, 450, 65))
        self.label.setStyleSheet("\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 30px;\n"
"line-height: 45px;\n"
"text-align: center;\n"
"\n"
"color: #1E2F97;\n"
"\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(120, 110, 171, 221))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(30, 2, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("\n"
"\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 18px;\n"
"line-height: 28px;\n"
"\n"
"color: #000000;\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setStyleSheet("\n"
"\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 18px;\n"
"line-height: 28px;\n"
"\n"
"color: #000000;\n"
"\n"
"")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setStyleSheet("\n"
"\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 18px;\n"
"line-height: 28px;\n"
"\n"
"color: #000000;\n"
"\n"
"")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setStyleSheet("\n"
"\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 18px;\n"
"line-height: 28px;\n"
"\n"
"color: #000000;\n"
"\n"
"")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setStyleSheet("\n"
"\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 18px;\n"
"line-height: 28px;\n"
"\n"
"color: #000000;\n"
"\n"
"")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setStyleSheet("\n"
"\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 18px;\n"
"line-height: 28px;\n"
"\n"
"color: #000000;\n"
"\n"
"")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.confirmButton = QtWidgets.QPushButton(self.frame)
        self.confirmButton.setGeometry(QtCore.QRect(210, 340, 111, 41))
        self.confirmButton.setStyleSheet("\n"
"background: #0026CA;\n"
"\n"
"border-radius: 10px;\n"
"\n"
"\n"
"\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 24px;\n"
"line-height: 28px;\n"
"text-align: center;\n"
"\n"
"color: #FFFFFF;\n"
"\n"
"")
        self.confirmButton.setObjectName("confirmButton")
        self.widget1 = QtWidgets.QWidget(self.frame)
        self.widget1.setGeometry(QtCore.QRect(290, 110, 92, 221))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.categoryLabel = QtWidgets.QLabel(self.widget1)
        self.categoryLabel.setStyleSheet("\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 16px;\n"
"line-height: 23px;\n"
"\n"
"color: rgba(0, 0, 0, 0.5);\n"
"\n"
"")
        self.categoryLabel.setObjectName("categoryLabel")
        self.verticalLayout_2.addWidget(self.categoryLabel)
        self.nameLabel = QtWidgets.QLabel(self.widget1)
        self.nameLabel.setStyleSheet("\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 16px;\n"
"line-height: 23px;\n"
"\n"
"color: rgba(0, 0, 0, 0.5);\n"
"\n"
"")
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout_2.addWidget(self.nameLabel)
        self.quantityLabel = QtWidgets.QLabel(self.widget1)
        self.quantityLabel.setStyleSheet("\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 16px;\n"
"line-height: 23px;\n"
"\n"
"color: rgba(0, 0, 0, 0.5);\n"
"\n"
"")
        self.quantityLabel.setObjectName("quantityLabel")
        self.verticalLayout_2.addWidget(self.quantityLabel)
        self.minimumLabel = QtWidgets.QLabel(self.widget1)
        self.minimumLabel.setStyleSheet("\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 16px;\n"
"line-height: 23px;\n"
"\n"
"color: rgba(0, 0, 0, 0.5);\n"
"\n"
"")
        self.minimumLabel.setObjectName("minimumLabel")
        self.verticalLayout_2.addWidget(self.minimumLabel)
        self.mediocreLabel = QtWidgets.QLabel(self.widget1)
        self.mediocreLabel.setStyleSheet("\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 16px;\n"
"line-height: 23px;\n"
"\n"
"color: rgba(0, 0, 0, 0.5);\n"
"\n"
"")
        self.mediocreLabel.setObjectName("mediocreLabel")
        self.verticalLayout_2.addWidget(self.mediocreLabel)
        self.lowLabel = QtWidgets.QLabel(self.widget1)
        self.lowLabel.setStyleSheet("\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 16px;\n"
"line-height: 23px;\n"
"\n"
"color: rgba(0, 0, 0, 0.5);\n"
"\n"
"")
        self.lowLabel.setObjectName("lowLabel")
        self.verticalLayout_2.addWidget(self.lowLabel)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Medicine Insertion Successful"))
        self.label_2.setText(_translate("MainWindow", "Category:"))
        self.label_3.setText(_translate("MainWindow", "Name:"))
        self.label_4.setText(_translate("MainWindow", "Quantity:"))
        self.label_5.setText(_translate("MainWindow", "Minimum:"))
        self.label_6.setText(_translate("MainWindow", "Mediocre:"))
        self.label_7.setText(_translate("MainWindow", "Low:"))
        self.confirmButton.setText(_translate("MainWindow", "Confirm"))
        self.categoryLabel.setText(_translate("MainWindow", "<plaeholder>"))
        self.nameLabel.setText(_translate("MainWindow", "<plaeholder>"))
        self.quantityLabel.setText(_translate("MainWindow", "<plaeholder>"))
        self.minimumLabel.setText(_translate("MainWindow", "<plaeholder>"))
        self.mediocreLabel.setText(_translate("MainWindow", "<plaeholder>"))
        self.lowLabel.setText(_translate("MainWindow", "<plaeholder>"))
