# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patient.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class PatientScreenGui(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1231, 871)
        Frame.setStyleSheet("background-color:#EEEEEE")
        self.newPatientButton = QtWidgets.QPushButton(Frame)
        self.newPatientButton.setGeometry(QtCore.QRect(971, 31, 200, 60))
        self.newPatientButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.newPatientButton.setStyleSheet("background-color: #39FF14;\n"
"border:none;\n"
"font-family:Roboto;\n"
"font-size:18px;\n"
"font-weight:bold;\n"
"color: #FFFFFF;\n"
"border-radius:12px;\n"
"\n"
"\n"
"")
        self.newPatientButton.setInputMethodHints(QtCore.Qt.ImhNone)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/img/plus icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newPatientButton.setIcon(icon)
        self.newPatientButton.setIconSize(QtCore.QSize(30, 30))
        self.newPatientButton.setFlat(False)
        self.newPatientButton.setObjectName("newPatientButton")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.newPatientButton.setText(_translate("Frame", "     New Patient"))
import MainGUI.resources
